build-game:
   stage: build
   script:
      - make game
   artifacts:
      paths:
         - game

build-test:
   stage: build
   script:
      - make test
   artifacts:
      paths:
         - test

test-game:
   stage: test
   script:
      - test
      - make memcheck-test
      - make static
   artifacts:
      paths:
         - results.memcheck
         - results.static

pages:
   stage: deploy
   dependencies:
      - test
   script:
      - make coverage
   artifacts:
      paths:
         - coverage
      expire_in: 30 days
   only:
      - master

pages:
   stage: deploy
   script:
      - make docs
   artifacts:
      paths:
         - docs
      expire_in: 30 days
   only:
      - master

